name: run examples

on: [push]

jobs:
  code-tests:
    if: ${{ github.event_name == 'push' || github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    name: Run code tests
    # запустим, только если изменено что-то в code/
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check for code/ changes
        id: changes
        uses: dorny/paths-filter@v2
        with:
          filters: |
            code:
              - 'code/**'

      - name: Set up Python
        if: steps.changes.outputs.code == 'true'
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        if: steps.changes.outputs.code == 'true'
        run: |
          pip3 install -r code/requirements.txt

      - name: 🔁 Run analyzer on all examples
        run: |
          cd code
          bash run-examples.bash
